### ISSUE TITLE
Create a Login Page

### ISSUE THREAD

**Issue by naveenneel121** [naveenneel121/login-2424#1]
1. Create a **New Branch Called Dev** and implement below functionality.
2. Create an **index.html** page.
3. Update Two Text Fields i.e. **Username & Password**
4. Update a button wit **Login**
5. Add a Person **Image Avatar** in Image
6. A **Checkbox** with Remember Me
7. A **Cancel** Button.
8. Link with **Forgot Password.**

https://github.com/ravi2krishna/login-2424/blob/main/index.html

**Comment by ghost** [comment]
As per the plan the Login page has been designed.
